# Generated by Django 5.2.5 on 2025-08-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_user_alter_student_id_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
