# Generated by Django 5.2.5 on 2025-09-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image_path',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
